name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      if: github.event_name == 'push' || contains(github.event.pull_request.merged_by.login, 'dependabot')
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t <DOCKER_USERNAME>/guestbook-app:${{ github.sha }} .
        docker push <DOCKER_USERNAME>/guestbook-app:${{ github.sha }}
